version: '3.8'

services:
  nginx: 
    # restart: unless-stopped
    build:
        context: .
        dockerfile: ./docker/nginx/Dockerfile
    ports:
        - 80:80
        - 443:443
    volumes:
        - ./docker/nginx/production:/etc/nginx/conf.d
        - ./docker/nginx/certs:/etc/ssl/certs
        - ./docker/nginx/include:/etc/nginx/conf.d/include
        - static_volume:/usr/src/marketplace/django_static
        - media_volume:/usr/src/marketplace/store
    depends_on: 
        - backend
    stop_signal: SIGINT
    
  backend:
    image: awesomeproject
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./marketplace/:/usr/src/marketplace/
      - static_volume:/usr/src/marketplace/django_static
      - media_volume:/usr/src/marketplace/store
    # ports:
    #   - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - redis
      - celery
      - migrations
      - blockchain

  migrations:
    build: ./marketplace
    image: awesomeproject
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py createsuperuser --noinput ; python manage.py collectstatic --noinput"
    volumes:
      - ./marketplace/:/usr/src/marketplace/
      - static_volume:/usr/src/marketplace/django_static
    env_file:
      - ./.env.dev
    depends_on:
      - redis

  blockchain:
    build: ./blockchain
    image: awesomeblockchain
    command: sh -c "python blockchain.py --port 5000"
    env_file:
      - ./.env.dev
    volumes: 
      - ./blockchain/:/usr/src/blockchain/
    stop_signal: SIGINT

  redis:
    image: redis

  celery:
    image: awesomeproject
    command: sh -c "cd marketplace && celery --app blockchain worker --pool=solo"
    volumes:
      - ./marketplace/:/usr/src/marketplace/
    env_file:
      - ./.env.dev
    depends_on:
      - redis

volumes:
    static_volume: {}
    media_volume: {}