version: '3.8'

services:
  # nginx: 
  #   # restart: unless-stopped
  #   build:
  #       context: .
  #       dockerfile: ./docker/nginx/Dockerfile
  #   ports:
  #       - 80:80
  #   volumes:
  #       # - static_volume:/app/backend/server/django_static
  #       - ./docker/nginx/development:/etc/nginx/conf.d
  #   depends_on: 
  #       - backend
  #   stop_signal: SIGINT

  site:
    build: ./web-marketplace
    image: web-awesomeproject
    command: npm start
    volumes:
      - ./marketplace/:/usr/src/web-marketplace/
    ports:
      - 3000:3000

  web:
    image: awesomeproject
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./marketplace/:/usr/src/marketplace/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - redis
      - celery
      - migrations
      - blockchain


  migrations:
    build: ./marketplace
    image: awesomeproject
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py createsuperuser --noinput"
    volumes:
      - ./marketplace/:/usr/src/marketplace/
    env_file:
      - ./.env.dev
    depends_on:
      - redis

  blockchain:
    build: ./blockchain
    image: awesomeblockchain
    command: sh -c "python blockchain.py --port 5000"
    env_file:
      - ./.env.dev
    volumes: 
      - ./blockchain/:/usr/src/blockchain/
    stop_signal: SIGINT

  redis:
    image: redis

  celery:
    image: awesomeproject
    command: sh -c "cd marketplace && celery --app blockchain worker --pool=solo"
    volumes:
      - ./marketplace/:/usr/src/marketplace/
    env_file:
      - ./.env.dev
    depends_on:
      - redis