# Generated by Django 4.0.3 on 2022-03-27 10:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='User_buyer', to=settings.AUTH_USER_MODEL)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='SellableObject_item', to='market.sellableobject')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='User_seller', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConfirmedTransaction',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('buyer', models.CharField(max_length=100)),
                ('seller', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.sellableobject')),
            ],
        ),
    ]
