# Generated by Django 4.0.3 on 2022-04-19 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0002_rename_item_id_confirmedtransaction_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmedtransaction',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
