# Generated by Django 4.0.3 on 2022-03-28 21:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_sellableobject_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageObject',
            fields=[
                ('sellableobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='market.sellableobject')),
                ('object', models.ImageField(null=True, upload_to='store/images/')),
            ],
            options={
                'db_table': 'Images',
            },
            bases=('market.sellableobject',),
        ),
        migrations.CreateModel(
            name='MusicObject',
            fields=[
                ('sellableobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='market.sellableobject')),
                ('object', models.FileField(null=True, upload_to='store/music/')),
            ],
            options={
                'db_table': 'Music',
            },
            bases=('market.sellableobject',),
        ),
        migrations.AddField(
            model_name='sellableobject',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='sellableobject',
            name='is_sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sellableobject',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='sellableobject',
            name='owner',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sellableobject',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sellableobject',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sellableobject',
            name='name',
            field=models.TextField(default='unknown', max_length=1000),
        ),
    ]
